os:
  - linux
  # - osx
language: python
python:
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --deploy
# command to run tests
script:
  - pwd
  - ls
  # - pytest -v # or py.test for Python versions 3.5 and below
  - pytest -v --cov-report term --cov-report xml --cov=mass_replace tests/
  - ls
after_success:
  - coveralls
  - wily report
deploy:
  provider: pypi
  user: $FLIT_USERNAME
  password: $FLIT_PASSWORD
  server: $FLIT_INDEX_URL
  skip_existing: true
  on:
    branch: dev