# mass_replace config file
replace_on_all_types: TRUE
root_folder: mass_replace
filetypes:
  - txt
  - csv
  - dat
  - xml
  - xsd
replacement_pairs:
  new_text1: Lorem
  new_text2: ipsum
  new_text3: old_text3
